### ISSUE TITLE
Loader

### ISSUE THREAD

**Issue by Creazed** [raniesantos/chattier#1]
Hey,

I just want to say: **THANK YOU**! This project is like ... dafuq, it's awesome! You are a genius, keep on coding! But ... could you add a loader, so when a user is signed in, and lands on the home page, there you can see the non-signed in vue component. Please fix that :) And the time for the timeline.

**Comment by raniesantos** [comment]
Hi... uhhh, thanks I guess? This is my first ever attempt to use a javascript framework and my first ever single-page app. I'm still currently working on this so I know there is still a lot of missing features.

**Comment by Creazed** [comment]
No problem :) learning by doing
