### ISSUE TITLE
Your session has expired, please sign in again.

### ISSUE THREAD

**Issue by SaifulAzam** [raniesantos/chattier#26]
Having issue when i refresh the browser its auto logout and show this message "Your session has expired, please sign in again".

Is there any way to stop auto logout after refresh the browser until JWT refresh token expired time?

**Comment by raniesantos** [comment]
What browser are you using? Can you give me more details to work with to help me find the source of the problem?

**Comment by raniesantos** [comment]
@SaifulAzam have you fixed the problem? Please tell me so I can close the issue.

**Comment by raniesantos** [comment]
I'll close this for now, if you don't reopen it then I'll assume the problem was solved.
