### ISSUE TITLE
Blank page with javascript error

### ISSUE THREAD

**Issue by fmchan** [raniesantos/chattier#32]
app.js:1 Uncaught SyntaxError: Unexpected token <
once i start the project, there is just a blank page with javascript error shown above.
please help

**Comment by raniesantos** [comment]
What development environment are you using?

Laravel Homestead? Laravel Valet? XAMPP?

**Comment by raniesantos** [comment]
Follow the setup instructions on the [README](https://github.com/raniesantos/chattier/blob/master/README.md)

I usually get that error because I didn't compile the assets with Mix.
